# Generated by Django 6.1.1 on 2026-09-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mse', '0002_rename_property_properties'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Properties',
            new_name='Propert',
        ),
    ]
