# Generated by Django 6.1.1 on 2026-09-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mse', '0003_rename_properties_propert'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Propert',
            new_name='Property',
        ),
    ]
