# Generated by Django 6.1.1 on 2026-09-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mse', '0004_rename_propert_property'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Prope',
        ),
    ]
