# Generated by Django 6.1.1 on 2026-09-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mse', '0005_rename_property_prope'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prope',
            new_name='Property',
        ),
    ]
