# Generated by Django 6.1.1 on 2026-10-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_company',
            field=models.CharField(default='Not Provided', max_length=50),
            preserve_default=False,
        ),
    ]
